INSERT INTO
    [dbo].[MasterIdentityType]
VALUES
    (
        'MAT0001',
        'KTP',
        GETDATE(),
        'Wulung',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        'MAT0002',
        'Domisili',
        GETDATE(),
        'Wulung',
        NULL,
        NULL,
        NULL,
        NULL
    ),
    (
        'MAT0003',
        'Darurat',
        GETDATE(),
        'Wulung',
        NULL,
        NULL,
        NULL,
        NULL
    )